services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'bankporium_dev'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'